export const FETCH_MAP_MARKERS_REQUEST = 'FETCH_MAP_MARKERS_REQUEST';
export const FETCH_MAP_MARKERS_SUCCESS = 'FETCH_MAP_MARKERS_SUCCESS';
export const FETCH_MAP_MARKERS_FAILURE = 'FETCH_MAP_MARKERS_FAILURE';
export const UPDATE_MAP_MARKER = 'UPDATE_MAP_MARKER';
